[package]
name = "jotter-gui-preview"
version.workspace = true
edition.workspace = true

[dependencies]
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_12"] }
jotter-parser = { version = "0.1.0", path = "../../crates/parser" }
jotter-theming = { version = "0.1.0", path = "../../crates/theming" }
webkit6 = "0.6.1"
