[package]
name = "jotter-app"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_12"] }
jotter-editor = { version = "0.1.0", path = "../editor" }
jotter-parser = { version = "0.1.0", path = "../parser" }
jotter-preview = { version = "0.1.0", path = "../preview" }
jotter-theming = { version = "0.1.0", path = "../theming" }
