//! Generate a `GtkSourceView` 5 style scheme (XML) for the markdown editor.
//!
//! The scheme covers the editor surface (background, cursor, current line,
//! selection, gutter), the markdown syntax classes, and the generic `def:*`
//! classes used when a fenced code block is highlighted.

use crate::model::Theme;

impl Theme {
    /// Render a `GtkSourceView` 5 style scheme as XML, registerable with
    /// `StyleSchemeManager`.
    #[must_use]
    pub fn to_sourceview_scheme_xml(&self) -> String {
        let e = &self.editor;
        let s = &e.syntax;
        let code = &self.code;

        format!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
<style-scheme id=\"{id}\" name=\"{name}\" version=\"1.0\">\n\
  <author>jotter</author>\n\
  <description>Generated by jotter theming</description>\n\n\
  <style name=\"text\" foreground=\"{fg}\" background=\"{bg}\"/>\n\
  <style name=\"background-pattern\" background=\"{surface}\"/>\n\
  <style name=\"cursor\" foreground=\"{cursor}\"/>\n\
  <style name=\"current-line\" background=\"{current_line}\"/>\n\
  <style name=\"current-line-number\" foreground=\"{ln_current}\" background=\"{current_line}\"/>\n\
  <style name=\"line-numbers\" foreground=\"{ln}\" background=\"{bg}\"/>\n\
  <style name=\"right-margin\" foreground=\"{margin}\" background=\"{margin}\"/>\n\
  <style name=\"selection\" background=\"{selection}\"/>\n\
  <style name=\"bracket-match\" foreground=\"{strong}\" bold=\"true\"/>\n\n\
  <style name=\"markdown:header\" foreground=\"{heading}\" bold=\"true\"/>\n\
  <style name=\"markdown:emphasis\" foreground=\"{emphasis}\" italic=\"true\"/>\n\
  <style name=\"markdown:strong-emphasis\" foreground=\"{strong}\" bold=\"true\"/>\n\
  <style name=\"markdown:link-text\" foreground=\"{link}\" underline=\"single\"/>\n\
  <style name=\"markdown:url\" foreground=\"{link}\" underline=\"single\"/>\n\
  <style name=\"markdown:link-destination\" foreground=\"{link}\"/>\n\
  <style name=\"markdown:code\" foreground=\"{inline_code}\"/>\n\
  <style name=\"markdown:code-block\" foreground=\"{inline_code}\"/>\n\
  <style name=\"markdown:blockquote-marker\" foreground=\"{block_quote}\" italic=\"true\"/>\n\
  <style name=\"markdown:list-marker\" foreground=\"{list_marker}\" bold=\"true\"/>\n\
  <style name=\"markdown:horizontal-rule\" foreground=\"{thematic_break}\" bold=\"true\"/>\n\n\
  <style name=\"def:comment\" foreground=\"{comment}\" italic=\"true\"/>\n\
  <style name=\"def:keyword\" foreground=\"{kw}\" bold=\"true\"/>\n\
  <style name=\"def:string\" foreground=\"{str}\"/>\n\
  <style name=\"def:number\" foreground=\"{num}\"/>\n\
  <style name=\"def:function\" foreground=\"{func}\"/>\n\
  <style name=\"def:type\" foreground=\"{typ}\"/>\n\
  <style name=\"def:identifier\" foreground=\"{var}\"/>\n\
</style-scheme>\n",
            id = self.scheme_id(),
            name = self.scheme_name(),
            fg = e.foreground,
            bg = e.background,
            surface = self.chrome.surface,
            cursor = e.cursor,
            current_line = e.current_line,
            ln_current = e.line_number_current,
            ln = e.line_number,
            margin = e.right_margin,
            selection = e.selection,
            heading = s.heading,
            emphasis = s.emphasis,
            strong = s.strong,
            link = s.link,
            inline_code = s.inline_code,
            block_quote = s.block_quote,
            list_marker = s.list_marker,
            thematic_break = s.thematic_break,
            comment = s.comment,
            kw = code.keyword,
            str = code.string,
            num = code.number,
            func = code.function,
            typ = code.type_name,
            var = code.variable,
        )
    }
}
